### ISSUE TITLE
Lua - Day 2 - easy exercise spoiler

### ISSUE THREAD

**Issue by euang** [7lang/7morelang#1]
Strict.lua contains the answer to modifying strict_write() to allow deleting keys.

-- This version can delete keys
function strict_write(table, key, value)
   if _private[key] and value then
      error("Duplicate key: " .. key)
   else
      _private[key] = value
   end
end

**Comment by undees** [comment]
Hello, euang.

Thank you for writing. You're right; the code in the repo contains answers for some of the exercises in case folks got stuck.  (Perhaps we should put the words "spoiler alert" in a comment?)

--Ian
